### ISSUE TITLE
Content QA :: Developing on OpenShift

### ISSUE THREAD

**Issue by cedricclyburn** [openshift-instruqt/instruqt#1]
TODO: Review the converted content and check if commands are working, if not, go ahead and fix it in the source repo.

Main Instruqt Page: https://play.instruqt.com/openshift
Main Source Code: https://github.com/openshift-instruqt/instruqt

- [x] [Getting Started with OpenShift for Developers](https://play.instruqt.com/openshift/tracks/developing-on-openshift-getting-started) | [Track](https://github.com/openshift-instruqt/instruqt/blob/master/developing-on-openshift/getting-started/track.yml)
- [x] [Deploying Applications From Source](https://play.instruqt.com/openshift/tracks/developing-on-openshift-deploying-python) | [Track](https://github.com/openshift-instruqt/instruqt/blob/master/developing-on-openshift/deploying-python/track.yml)
- [x] [Developing with odo](https://play.instruqt.com/openshift/tracks/developing-on-openshift-developing-with-odo) | [Track](https://github.com/openshift-instruqt/instruqt/blob/master/developing-on-openshift/developing-with-odo/track.yml)
- [x] [Getting Started with OpenShift Serverless](https://play.instruqt.com/openshift/tracks/developing-on-openshift-serverless) | [Track](https://github.com/openshift-instruqt/instruqt/blob/master/developing-on-openshift/serverless/track.yml)
- [x] [Connecting to a Database Using Port Forwarding](https://play.instruqt.com/openshift/tracks/developing-on-openshift-port-forwarding) | [Track](https://github.com/openshift-instruqt/instruqt/blob/master/developing-on-openshift/port-forwarding/track.yml)
- [x] [Transferring Files in and out of Containers](https://play.instruqt.com/openshift/tracks/developing-on-openshift-transferring-files) | [Track](https://github.com/openshift-instruqt/instruqt/blob/master/developing-on-openshift/transferring-files/track.yml)
- [x] [Getting Started with Helm 3 on OpenShift](https://play.instruqt.com/openshift/tracks/developing-on-openshift-helm) | [Track](https://github.com/openshift-instruqt/instruqt/blob/master/developing-on-openshift/helm/track.yml)

**Comment by cedricclyburn** [comment]
#39 is the Mega PR, still WOP

**Comment by blues-man** [comment]
Fixed @dewan-ahmed @cedricclyburn
