### ISSUE TITLE
Content QA :: AI and Machine Learning

### ISSUE THREAD

**Issue by cedricclyburn** [openshift-instruqt/instruqt#10]
TODO: Review the converted content and check if commands are working, if not, go ahead and fix it in the source repo.

Main Instruqt Page: https://play.instruqt.com/openshift
Main Source Code: https://github.com/openshift-instruqt/instruqt

- [x] [Deploying a Jupyter Notebook Image](https://play.instruqt.com/openshift/tracks/ai-machine-learning-jupyter-notebooks) | [Track](https://github.com/openshift-instruqt/instruqt/blob/master/ai-machine-learning/jupyterhub-workspace/track.yml)
- [x] [Building Custom Notebook Images](https://play.instruqt.com/openshift/tracks/ai-machine-learning-custom-notebooks) | [Track](https://github.com/openshift-instruqt/instruqt/blob/master/ai-machine-learning/custom-notebooks/track.yml)
- [x] [Persistent Workspace for Notebooks](https://play.instruqt.com/openshift/tracks/ai-machine-learning-jupyter-workspace) | [Track](https://github.com/openshift-instruqt/instruqt/blob/master/ai-machine-learning/jupyter-workspace/track.yml)
- [x] [Deploying JupyterHub as a Service](https://play.instruqt.com/openshift/tracks/ai-machine-learning-jupyterhub-service) | [Track](https://github.com/openshift-instruqt/instruqt/blob/master/ai-machine-learning/jupyterhub-service/track.yml)
- [x] [Multi-user Workspace Using JupyterHub](https://play.instruqt.com/openshift/tracks/ai-machine-learning-jupyterhub-workspace) | [Track](https://github.com/openshift-instruqt/instruqt/blob/master/ai-machine-learning/jupyterhub-workspace/track.yml)
- [x] [Prometheus metrics for Data Science on OpenShift](https://play.instruqt.com/openshift/tracks/ai-machine-learning-prometheus-api-client) | [Track](https://github.com/openshift-instruqt/instruqt/blob/master/ai-machine-learning/prometheus-api-client/track.yml)
- [x] [Time series forecasting for Prometheus metrics](https://play.instruqt.com/openshift/tracks/ai-machine-learning-prometheus-timeseries-forecasting) | [Track](https://github.com/openshift-instruqt/instruqt/blob/master/ai-machine-learning/prometheus-timeseries-forecasting/track.yml)
- [x] [Thoth S2I build with Advise on OpenShift](https://play.instruqt.com/openshift/tracks/ai-machine-learning-thoth-s2i-advise) | [Track](https://github.com/openshift-instruqt/instruqt/blob/master/ai-machine-learning/thoth-s2i-advise/track.yml)
- [x] [Thoth S2I build with Provenance check on OpenShift](https://play.instruqt.com/openshift/tracks/ai-machine-learning-thoth-s2i-provenance) | [Track](https://github.com/openshift-instruqt/instruqt/blob/master/ai-machine-learning/thoth-s2i-provenance/track.yml)

**Comment by blues-man** [comment]
@mayaCostantini this is all fixed now, you see them listed here:
https://developers.redhat.com/courses/ai-ml

Btw getting this error for Thoth ones while running the build:

```    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: https://api.moc.thoth-station.ninja/api/v1
```

**Comment by mayaCostantini** [comment]
@blues-man Thank you for the fixes! I will check on the issue soon.
I think this URL is not active anymore or is not currently available, we are going to check on it and post what we found in this issue (cc @harshad16)

**Comment by mayaCostantini** [comment]
The URL which replaces https://api.moc.thoth-station.ninja/api/v1 is https://khemenu.thoth-station.ninja
