### ISSUE TITLE
EPIC: Content sync and update to OpenShift 4.10

### ISSUE THREAD

**Issue by ryanj** [openshift-instruqt/instruqt#105]
# OpenShift 4-10 release plan

1. Update each track
   1. Run `instruqt track push --force` from within a track folder to push the update
   2. Delete and re-create any hot_start settings for the track.  Clean up any leftover "v2" or "dev" tracks
2. Complete the following QA test plan for each track:
   1. Run `oc version` to make sure that the track is running on OpenShift v4.10
   2. Test to make sure that the track's command-line dependencies (`java`, `mvn`, etc) are available and are working according to documentation
   3. File bug reports for any issues that are found

#### [developing-with-quarkus/panache](https://play.instruqt.com/openshift/tracks/developing-with-quarkus-panache)
 - [x] Content Sync (`instruqt track push`)
 - [x] QA Pass 
#### [developing-on-openshift/getting-started](https://play.instruqt.com/openshift/tracks/developing-on-openshift-getting-started)
 - [x] Content Sync (`instruqt track push`)
 - [x] QA Pass 
#### [developing-with-quarkus/getting-started](https://play.instruqt.com/openshift/tracks/developing-with-quarkus-getting-started)
 - [x] Content Sync (`instruqt track push`)
 - [x] QA Pass 
#### [developing-with-quarkus/panache-reactive](https://play.instruqt.com/openshift/tracks/developing-with-quarkus-panache-reactive)
 - [x] Content Sync (`instruqt track push`)
 - [x] QA Pass 
#### [developing-with-quarkus/qute](https://play.instruqt.com/openshift/tracks/developing-with-quarkus-qute)
 - [x] Content Sync (`instruqt track push`)
 - [x] QA Pass
#### [using-the-cluster/deploying-images](https://play.instruqt.com/openshift/tracks/using-the-cluster-deploying-images)
 - [x] Content Sync (`instruqt track push`)
 - [x] QA Pass
#### [using-the-cluster/deploying-python](https://play.instruqt.com/openshift/tracks/using-the-cluster-deploying-python)
 - [x] Content Sync (`instruqt track push`)
 - [x] QA Pass
#### [developing-with-quarkus/kafka](https://play.instruqt.com/openshift/tracks/developing-with-quarkus-kafka)
 - [x] Content Sync (`instruqt track push`)
 - [x] QA Pass
#### [developing-with-quarkus/monitoring](https://play.instruqt.com/openshift/tracks/developing-with-quarkus-monitoring)
 - [x] Content Sync (`instruqt track push`)
 - [x] QA Pass
#### [developing-with-quarkus/spring](https://play.instruqt.com/openshift/tracks/developing-with-quarkus-spring)
 - [x] Content Sync (`instruqt track push`)
 - [x] QA Pass
#### [using-the-cluster/transferring-files](https://play.instruqt.com/openshift/tracks/using-the-cluster-transferring-files)
 - [x] Content Sync (`instruqt track push`)
 - [x] QA Pass
#### [using-the-cluster/port-forwarding](https://play.instruqt.com/openshift/tracks/using-the-cluster-port-forwarding)
 - [x] Content Sync (`instruqt track push`)
 - [x] QA Pass
#### [using-the-cluster/resource-objects](https://play.instruqt.com/openshift/tracks/using-the-cluster-resource-objects)
 - [x] Content Sync (`instruqt track push`)
 - [x] QA Pass
#### [developing-with-quarkus/reactive-sql](https://play.instruqt.com/openshift/tracks/developing-with-quarkus-reactive-sql)
 - [x] Content Sync (`instruqt track push`)
 - [ ] QA Pass
#### [using-the-cluster/cluster-access](https://play.instruqt.com/openshift/tracks/using-the-cluster-cluster-access)
 - [ ] Content Sync (`instruqt track push`)
 - [ ] QA Pass

**Comment by blues-man** [comment]
@ryanj should we track all tracks updates?

**Comment by ryanj** [comment]
@blues-man not sure what you mean.  Ping me in chat to discuss?
