### ISSUE TITLE
Content QA :: Linux Container Fundamentals

### ISSUE THREAD

**Issue by cedricclyburn** [openshift-instruqt/instruqt#11]
TODO: Review the converted content and check if commands are working, if not, go ahead and fix it in the source repo.

Main Instruqt Page: https://play.instruqt.com/openshift
Topic Page: https://play.instruqt.com/openshift/topics/linux-container-fundamentals/
Main Source Code: https://github.com/openshift-instruqt/instruqt

- [x] [Introduction to Containers](https://play.instruqt.com/openshift/tracks/subsystems-container-internals-lab-2-0-part-1) | [Track](https://github.com/openshift-instruqt/instruqt/blob/master/subsystems/container-internals-lab-2-0-part-1/track.yml)
- [x] [Container Images](https://play.instruqt.com/openshift/tracks/subsystems-container-internals-lab-2-0-part-2) | [Track](https://github.com/openshift-instruqt/instruqt/blob/master/subsystems/container-internals-lab-2-0-part-2/track.yml)
- [x] [Container Registries](https://play.instruqt.com/openshift/tracks/subsystems-container-internals-lab-2-0-part-3) | [Track](https://github.com/openshift-instruqt/instruqt/blob/master/subsystems/container-internals-lab-2-0-part-3/track.yml)
- [x] [Container Hosts](https://play.instruqt.com/openshift/tracks/subsystems-container-internals-lab-2-0-part-4) | [Track](https://github.com/openshift-instruqt/instruqt/blob/master/subsystems/container-internals-lab-2-0-part-4/track.yml)
- [x] [Container Orchestration](https://play.instruqt.com/openshift/tracks/subsystems-container-internals-lab-2-0-part-5) | [Track](https://github.com/openshift-instruqt/instruqt/blob/master/subsystems/container-internals-lab-2-0-part-5/track.yml)
- [x] [Container Standards](https://play.instruqt.com/openshift/tracks/subsystems-container-internals-lab-2-0-part-6) | [Track](https://github.com/openshift-instruqt/instruqt/blob/master/subsystems/container-internals-lab-2-0-part-6/track.yml)
- [x] [Container Tools Ecosystem](https://play.instruqt.com/openshift/tracks/subsystems-container-internals-lab-2-0-part-7) | [Track](https://github.com/openshift-instruqt/instruqt/blob/master/subsystems/container-internals-lab-2-0-part-7/track.yml)

**Comment by blues-man** [comment]
We need to update all tracks to use RHEL 8 image like in the [Container Tools Ecosystem](https://github.com/openshift-instruqt/instruqt/blob/master/subsystems/container-internals-lab-2-0-part-7/config.yml#L4)
