### ISSUE TITLE
Content QA :: Developing with Kogito

### ISSUE THREAD

**Issue by blues-man** [openshift-instruqt/instruqt#12]
TODO: Review the converted content and check if commands are working, if not, go ahead and fix it in the source repo.

Main Instruqt Page: https://play.instruqt.com/openshift
Main Source Code: https://github.com/openshift-instruqt/instruqt

- [ ] [Getting Started with Kogito](https://play.instruqt.com/openshift/tracks/developing-with-kogito-getting-started) | [Track](https://github.com/openshift-instruqt/instruqt/blob/master/developing-with-kogito/getting-started/track.yml)
- [ ] [Kogito and Rules with RuleUnits](https://play.instruqt.com/openshift/tracks/developing-with-kogito-rules) | [Track](https://github.com/openshift-instruqt/instruqt/blob/master/developing-with-kogito/rules/track.yml)
- [ ] [DMN decision services with Kogito](https://play.instruqt.com/openshift/tracks/developing-with-kogito-dmn) | [Track](https://github.com/openshift-instruqt/instruqt/blob/master/developing-with-kogito/dmn/track.yml)
- [ ] [Kogito and CDI](https://play.instruqt.com/openshift/tracks/developing-with-kogito-service-task-cdi) | [Track](https://github.com/openshift-instruqt/instruqt/blob/master/developing-with-kogito/service-task-cdi/track.yml)
- [ ] [Orchestrating RESTful Services with Kogito](https://play.instruqt.com/openshift/tracks/developing-with-kogito-rest-service-integration) | [Track](https://github.com/openshift-instruqt/instruqt/blob/master/developing-with-kogito/rest-service-integration/track.yml)
- [ ] [OptaPlanner and Quarkus](https://play.instruqt.com/openshift/tracks/developing-with-kogito-optaplanner-knapsack) | [Track](https://github.com/openshift-instruqt/instruqt/blob/master/developing-with-kogito/optaplanner-knapsack/track.yml)

**Comment by cedricclyburn** [comment]
These tracks have been archived due to limited usage, will possibly bring back in the future!
