### ISSUE TITLE
OpenShift 4-11 Migration

### ISSUE THREAD

**Issue by ryanj** [openshift-instruqt/instruqt#161]
Migrate all tracks to OpenShift 4.11.7

Goals for each track:
1. Update the `config.yml`, setting the `image` field to: `rhd-devx-instruqt/openshift-4-11-7-lgph7`
2. Copy [the `setup-crc` file from the playground track](https://raw.githubusercontent.com/openshift-instruqt/instruqt/master/playgrounds/openshift411/track_scripts/setup-crc) into your `track_scripts` folder
3. Update each of your `assignment.md` files to reference the new Web Console url setting: `url: https://console-openshift-console.crc-lgph7-master-0.crc.${_SANDBOX_ID}.instruqt.io`

Example PRs: https://github.com/openshift-instruqt/instruqt/pull/158, #167 

Successfully migrated:
- [x] [Getting Started with OpenShift for Developers](https://play.instruqt.com/openshift/tracks/developing-on-openshift-getting-started) #158 
- [x] [Developing with odo](https://play.instruqt.com/openshift/tracks/developing-on-openshift-developing-with-odo)
- [x] [OpenShift 4.11 Playground](https://play.instruqt.com/openshift/tracks/playgrounds-openshift411)
- [x] [Logging in to an OpenShift Cluster](https://play.instruqt.com/openshift/tracks/using-the-cluster-cluster-access)
- [x] [Transferring Files in and out of Containers](https://play.instruqt.com/openshift/tracks/using-the-cluster-transferring-files)
- [x] [Deploying Applications From Source](https://play.instruqt.com/openshift/tracks/deploying-applications-from-source)
- [x] [Using the CLI to Manage Resource Objects](https://play.instruqt.com/openshift/tracks/using-the-cluster-resource-objects)
- [x] [Reactive programming with Quarkus Reactive SQL](https://play.instruqt.com/openshift/tracks/developing-with-quarkus-reactive-sql) ✅ 
- [x] [Quarkus for Spring Boot Developers](https://play.instruqt.com/openshift/tracks/developing-with-quarkus-spring) ✅ (OpenShift Console did not load. Everything else was fine including `oc` CLI)
- [x] [Camel K Basics](https://play.instruqt.com/openshift/tracks/serverless-camel-k-basic) ✅ (OpenShift Console failed here too. Everything else was fine. The first Camel integration takes a solid couple of minutes to start. Worth noting in content, and seeing if we can do something to improve it)
- [x] [Kubernetes API Fundamentals](https://play.instruqt.com/openshift/tracks/operatorframework-k8s-api-fundamentals)
- [x] [Ansible Operator Overview](https://play.instruqt.com/openshift/tracks/operatorframework-ansible-operator-overview)
- [x] [Ansible Kubernetes Modules](https://play.instruqt.com/openshift/tracks/operatorframework-ansible-k8s-modules)
- [x] [Operator SDK with Go](https://play.instruqt.com/openshift/tracks/operatorframework-go-operator-podset) ✅
- [x] [Operator Lifecycle Manager](https://play.instruqt.com/openshift/tracks/operatorframework-operator-lifecycle-manager)
- [x] [Mcrouter Operator powered by Ansible Operator](https://play.instruqt.com/openshift/tracks/operatorframework-ansible-mcrouter-operator)
- [x] [Getting Started with ArgoCD and OpenShift GitOps Operator](https://play.instruqt.com/openshift/tracks/gitops-getting-started)
- [x] [Working with Kustomize](https://play.instruqt.com/openshift/tracks/gitops-kustomize)
- [x] [Working with Helm](https://play.instruqt.com/openshift/tracks/gitops-working-with-helm)
- [x] [Syncwaves and Hooks](https://play.instruqt.com/openshift/tracks/gitops-syncwaves-hooks)
- [x] [Using OpenShift Pipelines](https://play.instruqt.com/openshift/tracks/gitops-pipelines)
- [x] [Getting Started with OpenShift Serverless](https://play.instruqt.com/openshift/tracks/developing-on-openshift-serverless)
- [x] [Serverless Camel K](https://play.instruqt.com/openshift/tracks/serverless-camel-k-serving)
- [x] [Serverless Eventing with Camel K](https://play.instruqt.com/openshift/tracks/serverless-camel-k-eventing)
- [x] [Camel Kafka Connector Basics](https://play.instruqt.com/openshift/tracks/serverless-camel-kafka-connector)
- [x] [Connecting to a Database Using Port Forwarding](https://play.instruqt.com/openshift/tracks/connecting-to-a-database-using-port-forwarding)
- [x] [Getting Started with Spring](https://play.instruqt.com/openshift/tracks/developing-with-spring-spring-getting-started)
- [x] [Spring REST](https://play.instruqt.com/openshift/tracks/developing-with-spring-spring-rest-services)
- [x] [Externalized Configuration](https://play.instruqt.com/openshift/tracks/developing-with-spring-microservices-1)
- [x] [Spring Data with JPA/Hibernate](https://play.instruqt.com/openshift/tracks/developing-with-spring-spring-db-access)
- [x] [Spring Messaging with Red Hat AMQ](https://play.instruqt.com/openshift/tracks/developing-with-spring-spring-messaging)
- [x] [Monitoring Spring Applications on OpenShift](https://play.instruqt.com/openshift/tracks/developing-with-spring-monitoring)
- [x] [Templating with Qute Templating Engine](https://play.instruqt.com/openshift/tracks/developing-with-quarkus-qute)
- [x] [Apache Kafka basics](https://play.instruqt.com/openshift/tracks/kafka-kafka-basic)
- [x] [Debezium for change data capture](https://play.instruqt.com/openshift/tracks/kafka-kafka-debezium)
- [x] [Exposing Apache Kafka through the HTTP Bridge](https://play.instruqt.com/openshift/tracks/kafka-kafka-http-bridge)
- [x] [Apache Kafka with Reactive Messaging](https://play.instruqt.com/openshift/tracks/kafka-kafka-quarkus)
- [x] [Making Persistent Storage Calls in Your Application](https://play.instruqt.com/openshift/tracks/persistence-persistent-intro)
- [x] [Persistent Storage for Elasticsearch Powered by OpenShift Container Storage](https://play.instruqt.com/openshift/tracks/persistence-persistent-elasticsearch)
- [x] [Application Messaging with Openshift](https://play.instruqt.com/openshift/tracks/enterprise-java-amq-getting-started-broker)
- [x] [Jakarta EE 8 Development](https://play.instruqt.com/openshift/tracks/enterprise-java-middleware-javaee8)
- [x] [Red Hat Data Grid development](https://play.instruqt.com/openshift/tracks/enterprise-java-rhoar-getting-started-rhdg)
- [x] [Introduction to Containers](https://play.instruqt.com/openshift/tracks/subsystems-container-internals-lab-2-0-part-1) #169
- [x] [Container Images](https://play.instruqt.com/openshift/tracks/subsystems-container-internals-lab-2-0-part-2) #169
- [x] [Container Registries](https://play.instruqt.com/openshift/tracks/subsystems-container-internals-lab-2-0-part-3) #169
- [x] [Container Hosts](https://play.instruqt.com/openshift/tracks/subsystems-container-internals-lab-2-0-part-4) #169
- [x] [Container Orchestration](https://play.instruqt.com/openshift/tracks/subsystems-container-internals-lab-2-0-part-5) #169
- [x] [Container Standards](https://play.instruqt.com/openshift/tracks/subsystems-container-internals-lab-2-0-part-6) #169
- [x] [Container Tools Ecosystem](https://play.instruqt.com/openshift/tracks/subsystems-container-internals-lab-2-0-part-7) #169
- Cedric
- [x] [Transferring Files in and out of Containers](https://play.instruqt.com/openshift/tracks/transferring-files-in-and-out-of-containers) #167 ✅ (Many images broken however
- [x] [Getting Started with Quarkus](https://play.instruqt.com/openshift/tracks/developing-with-quarkus-getting-started) #167 ✅
- [x] [Deploying Applications From Source](https://play.instruqt.com/openshift/tracks/using-the-cluster-deploying-python) #167 (Still on 4.10, maybe hasn't been pushed yet?)
- [x] [Deploying Applications From Images](https://play.instruqt.com/openshift/tracks/using-the-cluster-deploying-images) #167 (Still on 4.10, maybe hasn't been pushed yet?)
- Natale
- [x] [Reactive Streaming with Quarkus and Kafka](https://play.instruqt.com/openshift/tracks/developing-with-quarkus-kafka) #167
- [x] [Monitoring Quarkus with Micrometer](https://play.instruqt.com/openshift/tracks/developing-with-quarkus-monitoring) #167
- [x] [Implementing a reactive application using Quarkus, Hibernate Reactive and Panache](https://play.instruqt.com/openshift/tracks/developing-with-quarkus-panache-reactive) #167
- [x] [Effective Data with Hibernate and Panache](https://play.instruqt.com/openshift/tracks/developing-with-quarkus-panache) #167
- Josh 
- [x] [Etcd Operator](https://play.instruqt.com/openshift/tracks/operatorframework-etcd-operator)
- [x] [Operator SDK with Helm](https://play.instruqt.com/openshift/tracks/operatorframework-helm-operator)
- [x] [Operator SDK with Helm, Memcached](https://play.instruqt.com/openshift/tracks/operatorframework-helm-operator-memcached)
- [x] [Operator SDK with Go, Memcached](https://play.instruqt.com/openshift/tracks/operatorframework-go-operator-memcached)
- Evan
- [x] [Getting Started with Helm 3 on OpenShift](https://play.instruqt.com/openshift/tracks/developing-on-openshift-helm)✅ (Encountered a very minor issue unrelated to migration. Check issue #174)

Duplicate content (Removed from Drupal, deleted on Instruqt):
- [x] [Getting Started with OpenShift Serverless](https://play.instruqt.com/openshift/tracks/serverless-serverless)
- [x] [Deploying Applications From Source](https://play.instruqt.com/openshift/tracks/deploying-applications-from-source)
- [x] [Getting Started with Quarkus](https://play.instruqt.com/openshift/tracks/getting-started-with-quarkus)
- [x] [Transferring Files in and out of containers](https://play.instruqt.com/openshift/tracks/using-the-cluster-transferring-files) (Need to replace current iframe with this one, the current is a duplicate we don't have access to
- [x] [Transferring Files in and out of containers](https://play.instruqt.com/openshift/tracks/transferring-files-in-and-out-of-containers)
- [x] [Using the CLI to Manage Resource Objects](https://play.instruqt.com/openshift/tracks/using-the-cli-to-manage-resource-objects)
- [x] [Working with the Instruqt interactive learning environment](https://play.instruqt.com/openshift/tracks/working-with-the-instruqt)

Preparing for Deletion (Needs to be removed from Drupal, deleted on Instruqt):
- [x] [Building Custom Notebook Images](https://play.instruqt.com/openshift/tracks/ai-machine-learning-custom-notebooks)
- [x] [Deploying a Jupyter Notebook Image](https://play.instruqt.com/openshift/tracks/ai-machine-learning-jupyter-notebooks)
- [x] [Persistent Workspace for Notebooks](https://play.instruqt.com/openshift/tracks/ai-machine-learning-jupyter-workspace)
- [x] [Deploying JupyterHub as a Service](https://play.instruqt.com/openshift/tracks/ai-machine-learning-jupyterhub-service)
- [x] [Multi-user Workspace Using JupyterHub](https://play.instruqt.com/openshift/tracks/ai-machine-learning-jupyterhub-workspace)
- [x] [Prometheus metrics for Data Science on OpenShift](https://play.instruqt.com/openshift/tracks/ai-machine-learning-prometheus-api-client)
- [x] [Time series forecasting for Prometheus metrics](https://play.instruqt.com/openshift/tracks/ai-machine-learning-prometheus-timeseries-forecasting)
- [x] [DMN decision services with Kogito](https://play.instruqt.com/openshift/tracks/developing-with-kogito-dmn)
- [x] [Getting Started with Kogito](https://play.instruqt.com/openshift/tracks/developing-with-kogito-getting-started)
- [x] [OptaPlanner and Quarkus](https://play.instruqt.com/openshift/tracks/developing-with-kogito-optaplanner-knapsack)
- [x] [Orchestrating RESTful Services with Kogito](https://play.instruqt.com/openshift/tracks/developing-with-kogito-rest-service-integration)
- [x] [Kogito and Rules with RuleUnits](https://play.instruqt.com/openshift/tracks/developing-with-kogito-rules)
- [x] [Kogito and CDI](https://play.instruqt.com/openshift/tracks/developing-with-kogito-service-task-cdi)
- [x] [Thoth S2I build with Advise on OpenShift](https://play.instruqt.com/openshift/tracks/ai-machine-learning-thoth-s2i-advise)
- [x] [Thoth S2I build with Provenance check on OpenShift](https://play.instruqt.com/openshift/tracks/ai-machine-learning-thoth-s2i-provenance)
- [x] [Getting Started with Camel K](https://play.instruqt.com/openshift/tracks/enterprise-java-camel-k-basic)
- [x] [Connecting to a Database Using Port Forwarding](https://play.instruqt.com/openshift/tracks/using-the-cluster-port-forwarding)
- [x] [OpenShift CodeReady Containers Test](https://play.instruqt.com/openshift/tracks/crc490-openshift-test)
- [x] [OpenShift CodeReady Containers without Nested Virt](https://play.instruqt.com/openshift/tracks/crc-test)
- [x] [Persistent Workspace for Notebooks](https://play.instruqt.com/openshift/tracks/ai-machine-learning-jupyter-workspace)
- [x] [ROSA Cluster Creation](https://play.instruqt.com/openshift/tracks/rosa-cluster-creation)
- [x] [ROSA with RHODS](https://play.instruqt.com/openshift/tracks/rosa-with-rhods)
- [x] [getting-started-4-10](https://play.instruqt.com/openshift/tracks/getting-started-4-10)
- [x] [Red Hat OpenShift Service Mesh and Istio Playground](https://play.instruqt.com/openshift/tracks/servicemesh-1-introduction)
- [x] [my copy camel k basic](https://play.instruqt.com/openshift/tracks/my-copy-camel-k-basic)
- [x] [odo-new](https://play.instruqt.com/openshift/tracks/odo-new)
- [x] [operatorsdk-fix](https://play.instruqt.com/openshift/tracks/operatorsdk-fix)
- [x] [playground-plain](https://play.instruqt.com/openshift/tracks/playground-plain)
- [x] [test](https://play.instruqt.com/openshift/tracks/test-crc)

Fully Deleted (Removed from Drupal & Instruqt):
- [ ] [OpenShift 4.9 Playground](https://play.instruqt.com/openshift/tracks/playgrounds-openshift49)
- [x] [Playground test](https://play.instruqt.com/openshift/tracks/playground-test)
- [x] [411-short-init](https://play.instruqt.com/openshift/tracks/411-short-init)
- [x] [Getting Started with Vert.x](https://play.instruqt.com/openshift/tracks/developing-with-vertx-getting-started-vertx)
- [x] [MicroTrader App Part 1: Quote Generator](https://play.instruqt.com/openshift/tracks/developing-with-vertx-quote-generator)
- [x] [MicroTrader App Part 2: Portfolio Service](https://play.instruqt.com/openshift/tracks/developing-with-vertx-portfolio-service)
- [x] [MicroTrader App Part 3: Compulsive Traders](https://play.instruqt.com/openshift/tracks/developing-with-vertx-compulsive-traders)
- [x] [MicroTrader App Part 4: Audit Service](https://play.instruqt.com/openshift/tracks/developing-with-vertx-audit-service)

**Comment by cedricclyburn** [comment]
Before migrating with #167 need to fix KUBECONFIG issue on 4.11 tracks:
![image](https://user-images.githubusercontent.com/54345140/202013814-30d40e70-5bd7-4a72-a527-db5cdf518096.png)
(This one specifically is [Getting Started with OpenShift for Developers](https://play.instruqt.com/openshift/tracks/developing-on-openshift-getting-started))

**Comment by ryanj** [comment]
This login bug should be fixed with https://github.com/openshift-instruqt/instruqt/commit/321c138525ff7cc575a8d8ab8dec4722f233389b

**Comment by cedricclyburn** [comment]
@cedricclyburn Add all duplicates ready to delete to main comment above ^

**Comment by cedricclyburn** [comment]
Added all duplicates + legacy tracks that aren't used

**Comment by cedricclyburn** [comment]
Removed all duplicate content & content ready for deletion from list above, & merging removal of tracks from main repo

**Comment by ryanj** [comment]
Thanks for the help on this one!
