### ISSUE TITLE
Content QA :: GitOps

### ISSUE THREAD

**Issue by cedricclyburn** [openshift-instruqt/instruqt#2]
TODO: Review the converted content and check if commands are working, if not, go ahead and fix it in the source repo.

Main Instruqt Page: https://play.instruqt.com/openshift
Topic Page: https://play.instruqt.com/openshift/topics/gitops
Main Source Code: https://github.com/openshift-instruqt/instruqt

- [x] [Using OpenShift Pipelines](https://play.instruqt.com/openshift/tracks/gitops-pipelines) | [Track](https://github.com/openshift-instruqt/instruqt/blob/master/gitops/pipelines/track.yml)
- [x] [Getting Started with ArgoCD and OpenShift GitOps Operator](https://play.instruqt.com/openshift/tracks/gitops-getting-started) | [Track](https://github.com/openshift-instruqt/instruqt/blob/master/gitops/getting-started/track.yml)
- [x] [Working with Kustomize](https://play.instruqt.com/openshift/tracks/gitops-kustomize) | [Track](https://github.com/openshift-instruqt/instruqt/blob/master/gitops/kustomize/track.yml)
- [x] [Syncwaves and Hooks](https://play.instruqt.com/openshift/tracks/gitops-syncwaves-hooks) | [Track](https://github.com/openshift-instruqt/instruqt/blob/master/gitops/syncwaves-hooks/track.yml)
- [x] [Working with Helm](https://play.instruqt.com/openshift/tracks/gitops-working-with-helm) | [Track](https://github.com/openshift-instruqt/instruqt/blob/master/gitops/working-with-helm/track.yml)

**Comment by dewan-ahmed** [comment]
https://github.com/openshift-instruqt/instruqt/pull/22 is the mega PR for all these tasks.
