### ISSUE TITLE
Content QA :: Kafka

### ISSUE THREAD

**Issue by cedricclyburn** [openshift-instruqt/instruqt#3]
TODO: Review the converted content and check if commands are working, if not, go ahead and fix it in the source repo.

Main Instruqt Page: https://play.instruqt.com/openshift
Topic Page: https://play.instruqt.com/openshift/topics/kafka
Main Source Code: https://github.com/openshift-instruqt/instruqt

- [x] [Apache Kafka basics](https://play.instruqt.com/openshift/tracks/kafka-kafka-basic) | [Track](https://github.com/openshift-instruqt/instruqt/blob/master/developing-on-openshift/getting-started/track.yml)
- [x] [Exposing Apache Kafka through the HTTP Bridge](https://play.instruqt.com/openshift/tracks/kafka-kafka-http-bridge) | [Track](https://github.com/openshift-instruqt/instruqt/blob/master/kafka/kafka-http-bridge/track.yml)
- [x] [Apache Kafka with Reactive Messaging](https://play.instruqt.com/openshift/tracks/kafka-kafka-quarkus) | [Track](https://github.com/openshift-instruqt/instruqt/blob/master/kafka/kafka-quarkus/track.yml)
- [x] [Debezium for change data capture](https://play.instruqt.com/openshift/tracks/kafka-kafka-debezium) | [Track](https://github.com/openshift-instruqt/instruqt/blob/master/kafka/kafka-debezium/track.yml)

**Comment by blues-man** [comment]
@hguerrero labs are ready for Lab author/maintainer TEST if you have any availability

- [ ] [Apache Kafka basics](https://play.instruqt.com/openshift/tracks/kafka-kafka-basic) | [Track](https://github.com/openshift-instruqt/instruqt/blob/master/developing-on-openshift/getting-started/track.yml)
- [ ] [Exposing Apache Kafka through the HTTP Bridge](https://play.instruqt.com/openshift/tracks/kafka-kafka-http-bridge) | [Track](https://github.com/openshift-instruqt/instruqt/blob/master/kafka/kafka-http-bridge/track.yml)
- [ ] [Apache Kafka with Reactive Messaging](https://play.instruqt.com/openshift/tracks/kafka-kafka-quarkus) | [Track](https://github.com/openshift-instruqt/instruqt/blob/master/kafka/kafka-quarkus/track.yml)
- [ ] [Debezium for change data capture](https://play.instruqt.com/openshift/tracks/kafka-kafka-debezium) | [Track](https://github.com/openshift-instruqt/instruqt/blob/master/kafka/kafka-debezium/track.yml)

**Comment by cedricclyburn** [comment]
Tracks have been migrated and upgraded, closing out issue 👍
