### ISSUE TITLE
Content QA :: Quarkus

### ISSUE THREAD

**Issue by cedricclyburn** [openshift-instruqt/instruqt#4]
TODO: Review the converted content and check if commands are working, if not, go ahead and fix it in the source repo.

Main Instruqt Page: https://play.instruqt.com/openshift
Main Source Code: https://github.com/openshift-instruqt/instruqt

- [x] [Getting Started with Quarkus](https://play.instruqt.com/openshift/tracks/developing-with-quarkus-getting-started) | [Track](https://github.com/openshift-instruqt/instruqt/blob/master/developing-with-quarkus/getting-started/track.yml)
- [x] [Reactive Streaming with Quarkus and Kafka](https://play.instruqt.com/openshift/tracks/developing-with-quarkus-kafka) | [Track](https://github.com/openshift-instruqt/instruqt/blob/master/developing-with-quarkus/kafka/track.yml)
- [x] [Quarkus for Spring Boot Developers](https://play.instruqt.com/openshift/tracks/developing-with-quarkus-spring) | [Track](https://github.com/openshift-instruqt/instruqt/blob/master/developing-with-quarkus/spring/track.yml)
- [x] [Templating with Qute Templating Engine](https://play.instruqt.com/openshift/tracks/developing-with-quarkus-qute) | [Track](https://github.com/openshift-instruqt/instruqt/blob/master/developing-with-quarkus/qute/track.yml)
- [x] [Monitoring Quarkus with Micrometer](https://play.instruqt.com/openshift/tracks/developing-with-quarkus-monitoring) | [Track](https://github.com/openshift-instruqt/instruqt/blob/master/developing-with-quarkus/monitoring/track.yml)
- [x] [Reactive programming with Quarkus Reactive SQL](https://play.instruqt.com/openshift/tracks/developing-with-quarkus-reactive-sql) | [Track](https://github.com/openshift-instruqt/instruqt/blob/master/developing-with-quarkus/reactive-sql/track.yml)
- [x] [Effective Data with Hibernate and Panache](https://play.instruqt.com/openshift/tracks/developing-with-quarkus-panache) | [Track](https://github.com/openshift-instruqt/instruqt/blob/master/developing-with-quarkus/panache/track.yml)
- [x] [Reactive Data access with Quarkus Hibernate Reactive with Panache](https://play.instruqt.com/openshift/tracks/developing-with-quarkus-panache-reactive) | [Track](https://github.com/openshift-instruqt/instruqt/blob/master/developing-with-quarkus/panache-reactive/track.yml)

**Comment by blues-man** [comment]
@edeandrea @danieloh30 @jamesfalkner could you please give me your +1 or comment/PR for the labs? Thanks!

**Comment by danieloh30** [comment]
Lab maintainer TEST
- [x] Getting Started with Quarkus
- [x] Reactive Streaming with Quarkus and Kafka
- [x] Quarkus for Spring Boot Developers
- [x] Templating with Qute Templating Engine
- [x] Monitoring Quarkus with Micrometer
- [x] Reactive programming with Quarkus Reactive SQL
- [x] Effective Data with Hibernate and Panache
- [x] Reactive Data access with Quarkus Hibernate Reactive with Panache

**Comment by danieloh30** [comment]
@blues-man I finished dry-run all quarkus tracks as well as improved contents and screenshots. I think you probably need to fix the LE issue(https://github.com/openshift-instruqt/instruqt/issues/42) before we make it public.

Also, some steps/challenges might be improved or changed related to Dev Mode/Remote Dev Mode since a student has to rerun it when a new challenge starts which seems not a live coding.

If you want me to close this epic, I'm happy to :)
