### ISSUE TITLE
Content QA :: Serverless

### ISSUE THREAD

**Issue by cedricclyburn** [openshift-instruqt/instruqt#5]
TODO: Review the converted content and check if commands are working, if not, go ahead and fix it in the source repo.

Main Instruqt Page: https://play.instruqt.com/openshift
Main Source Code: https://github.com/openshift-instruqt/instruqt

- [ ] [Getting Started with OpenShift Serverless](https://play.instruqt.com/openshift/tracks/serverless-serverless) | [Track](https://github.com/openshift-instruqt/instruqt/blob/master/serverless/serverless/track.yml)
- [ ] Application Messaging with OpenShift (Broken)
- [ ] [Camel K Basics](https://play.instruqt.com/openshift/tracks/developing-with-quarkus-spring) | [Track](https://github.com/openshift-instruqt/instruqt/blob/master/serverless/camel-k-basic/track.yml)
- [ ] [Serverless Camel K](https://play.instruqt.com/openshift/tracks/serverless-camel-k-serving) | [Track](https://github.com/openshift-instruqt/instruqt/blob/master/serverless/camel-k-serving/track.yml)
- [ ] [Serverless Eventing with Camel K](https://play.instruqt.com/openshift/tracks/serverless-camel-k-eventing) | [Track](https://github.com/openshift-instruqt/instruqt/blob/master/serverless/camel-k-eventing/track.yml)
- [ ] [Camel Kafka Connector Basics](https://play.instruqt.com/openshift/tracks/serverless-camel-kafka-connector) | [Track](https://github.com/openshift-instruqt/instruqt/blob/master/serverless/camel-kafka-connector/track.yml)

**Comment by cedricclyburn** [comment]
Tracks have been migrated, closing this issue out!
