### ISSUE TITLE
Content QA :: OpenShift Basics

### ISSUE THREAD

**Issue by cedricclyburn** [openshift-instruqt/instruqt#6]
TODO: Review the converted content and check if commands are working, if not, go ahead and fix it in the source repo.

Main Instruqt Page: https://play.instruqt.com/openshift
Main Source Code: https://github.com/openshift-instruqt/instruqt

- [x] [Logging in to an OpenShift Cluster](https://play.instruqt.com/openshift/tracks/using-the-cluster-cluster-access) | [Track](https://github.com/openshift-instruqt/instruqt/blob/master/using-the-cluster/cluster-access/track.yml)
- [x] [Transferring Files in and out of Containers](https://play.instruqt.com/openshift/tracks/developing-on-openshift-transferring-files) | [Track](https://github.com/openshift-instruqt/instruqt/blob/master/using-the-cluster/transferring-files/track.yml)
- [x] [Connecting to a Database Using Port Forwarding](https://play.instruqt.com/openshift/tracks/using-the-cluster-port-forwarding) | [Track](https://github.com/openshift-instruqt/instruqt/blob/master/using-the-cluster/port-forwarding/track.yml)
- [x] [Using the CLI to Manage Resource Objects](https://play.instruqt.com/openshift/tracks/using-the-cluster-resource-objects) | [Track](https://github.com/openshift-instruqt/instruqt/blob/master/using-the-cluster/resource-objects/track.yml)
- [x] [Deploying Applications From Images](https://play.instruqt.com/openshift/tracks/using-the-cluster-deploying-images) | [Track](https://github.com/openshift-instruqt/instruqt/blob/master/using-the-cluster/deploying-images/track.yml)
- [x] [Deploying Applications From Source](https://play.instruqt.com/openshift/tracks/using-the-cluster-deploying-python) | [Track](https://github.com/openshift-instruqt/instruqt/blob/master/using-the-cluster/deploying-python/track.yml)
- [ ] [How to set up Prometheus and Grafana on OpenShift](https://play.instruqt.com/openshift/tracks/using-the-cluster-deploy-prometheus-grafana) | [Track](https://github.com/openshift-instruqt/instruqt/blob/master/using-the-cluster/deploy-prometheus-grafana/track.yml)

**Comment by cedricclyburn** [comment]
Note: Need to update the redirect, many of these courses are legacy duplicates

**Comment by cedricclyburn** [comment]
Closing out these tracks as they've been migrated and upgraded 👍
