### ISSUE TITLE
Content QA :: Operators

### ISSUE THREAD

**Issue by cedricclyburn** [openshift-instruqt/instruqt#7]
TODO: Review the converted content and check if commands are working, if not, go ahead and fix it in the source repo.

Main Instruqt Page: https://play.instruqt.com/openshift
Main Source Code: https://github.com/openshift-instruqt/instruqt

- [x] [Kubernetes API Fundamentals](https://play.instruqt.com/openshift/tracks/operatorframework-k8s-api-fundamentals) | [Track](https://github.com/openshift-instruqt/instruqt/blob/master/operatorframework/k8s-api-fundamentals/track.yml)
- [x] [Etcd Operator](https://play.instruqt.com/openshift/tracks/operatorframework-etcd-operator) | [Track](https://github.com/openshift-instruqt/instruqt/blob/master/operatorframework/etcd-operator/track.yml) 
- [x] [Operator SDK with Go](https://play.instruqt.com/openshift/tracks/operatorframework-go-operator-podset) | [Track](https://github.com/openshift-instruqt/instruqt/blob/master/operatorframework/go-operator-podset/track.yml)
- [x] [Operator Lifecycle Manager](https://play.instruqt.com/openshift/tracks/operatorframework-operator-lifecycle-manager) | [Track](https://github.com/openshift-instruqt/instruqt/blob/master/operatorframework/operator-lifecycle-manager/track.yml)
- [x] [Ansible Kubernetes Modules](https://play.instruqt.com/openshift/tracks/operatorframework-ansible-k8s-modules) | [Track](https://github.com/openshift-instruqt/instruqt/blob/master/operatorframework/ansible-k8s-modules/track.yml)
- [x] [Ansible Operator Overview](https://play.instruqt.com/openshift/tracks/operatorframework-ansible-operator-overview) | [Track](https://github.com/openshift-instruqt/instruqt/blob/master/operatorframework/ansible-operator-overview/track.yml) 
- [x] [Mcrouter Operator powered by Ansible Operator](https://play.instruqt.com/openshift/tracks/operatorframework-ansible-mcrouter-operator) | [Track](https://github.com/openshift-instruqt/instruqt/blob/master/operatorframework/ansible-mcrouter-operator/track.yml) 
- [x] [Operator SDK with Helm](https://play.instruqt.com/openshift/tracks/operatorframework-helm-operator) | [Track](https://github.com/openshift-instruqt/instruqt/blob/master/operatorframework/helm-operator/track.yml)
- [x] [Operator SDK with Go, Memcached](https://play.instruqt.com/openshift/tracks/operatorframework-go-operator-memcached) | [Track](https://github.com/openshift-instruqt/instruqt/blob/master/operatorframework/go-operator-memcached/track.yml)
- [x] [Operator SDK with Helm, Memcached](https://play.instruqt.com/openshift/tracks/operatorframework-helm-operator-memcached) | [Track](https://github.com/openshift-instruqt/instruqt/blob/master/operatorframework/helm-operator-memcached/track.yml)

**Comment by joshix** [comment]
Operator Lifecycle Manager and Operator SDK with go-memcached should get a final look but are otherwise check-mark-able after merge of https://github.com/openshift-instruqt/instruqt/pull/18

**Comment by blues-man** [comment]
EtcdOperator is bloked by this: https://github.com/openshift-instruqt/instruqt/issues/19
