### ISSUE TITLE
Content QA :: Spring/Spring Boot

### ISSUE THREAD

**Issue by cedricclyburn** [openshift-instruqt/instruqt#8]
TODO: Review the converted content and check if commands are working, if not, go ahead and fix it in the source repo.

Main Instruqt Page: https://play.instruqt.com/openshift
Topic Page: https://play.instruqt.com/openshift/topics/developing-with-spring
Main Source Code: https://github.com/openshift-instruqt/instruqt

- [x] [Getting Started with Spring](https://play.instruqt.com/openshift/tracks/developing-with-spring-spring-getting-started) | [Track](https://github.com/openshift-instruqt/instruqt/blob/master/developing-with-spring/spring-getting-started/track.yml)
- [x] [Spring REST](https://play.instruqt.com/openshift/tracks/developing-with-spring-spring-rest-services) | [Track](https://github.com/openshift-instruqt/instruqt/blob/master/developing-with-spring/spring-rest-services/track.yml)
- [x] [Spring Data with JPA/Hibernate](https://play.instruqt.com/openshift/tracks/developing-with-spring-spring-db-access) | [Track](https://github.com/openshift-instruqt/instruqt/blob/master/developing-with-spring/spring-db-access/track.yml)
- [x] [Spring Messaging with Red Hat AMQ](https://play.instruqt.com/openshift/tracks/developing-with-spring-spring-messaging) | [Track](https://github.com/openshift-instruqt/instruqt/blob/master/developing-with-spring/spring-messaging/track.yml)
- [x] [Externalized Configuration](https://play.instruqt.com/openshift/tracks/developing-with-spring-microservices-1) | [Track](https://github.com/openshift-instruqt/instruqt/blob/master/developing-with-spring/microservices-1/track.yml)
- [x] [Monitoring Spring Applications on OpenShift](https://play.instruqt.com/openshift/tracks/developing-with-spring-monitoring) | [Track](https://github.com/openshift-instruqt/instruqt/blob/master/developing-with-spring/monitoring/track.yml)

**Comment by Pragya001** [comment]
@dewan-ahmed  
Hi Ahmed,
Are you working on the issue?

**Comment by dewan-ahmed** [comment]
Hi @Pragya001 yes I'm starting on these tracks today.

**Comment by blues-man** [comment]
@danieloh30 labs are ready for Lab maintainer TEST
- [x] Getting Started with Spring
- [x] Spring REST
- [x] Spring Data with JPA/Hibernate
- [x] Spring Messaging with Red Hat AMQ
- [x] Externalized Configuration
- [x] Monitoring Spring Applications on OpenShift

**Comment by danieloh30** [comment]
Cool. I will start this next Monday after Thanksgivings :)

**Comment by danieloh30** [comment]
Ok. I just finished all tracks with minor improvements. I also double-checked the image migration which looks good to me.

**Comment by danieloh30** [comment]
I also keep having the same error when I run the app via maven:
```
[ERROR] Failed to execute goal on project spring-messaging-training: Could not resolve dependencies for project com.example:spring-messaging-training:jar:0.0.1-SNAPSHOT: The following artifacts could not be resolved: 
```

**Comment by blues-man** [comment]
@danieloh30 I'm not sure if that is for a temp CDN issue or we need any additional settings.xml we missed?
